[package]
name = "rolling_stats"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "rolling_stats"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34.0"
dashmap = "6.1.0"
